### ISSUE TITLE
Error during Maven build

### ISSUE THREAD

**Issue by CreaRo** [fommil/foolish-football#52]
I've compiled the game successfully using `mvn -pl game compile`. 
However, on running `mvn -pl game exec:exec -e -X` I get the following build error - 

```
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project game: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project game: Command execution failed.
```

How do I fix this?

**Comment by fommil** [comment]
I haven't looked at this project in a long time but I just tried the command and it works. You haven't copied all the output, in particular you've asked for exception information but skipped the exception.

**Comment by CreaRo** [comment]
The exception I get is exactly the same as the one in [this](https://github.com/alexa/alexa-avs-raspberry-pi/issues/69) thread (its a completely different project but the problem seems to be the same)

I didn't want to fill up the page with the huge output, but yes I did forget to put the exception, haha.
Here's the entire output.

    DEBUG] Executing command line: java -ea -Djava.util.logging.config.file=logging.properties -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -Djava.library.path=native -classpath /home/rish/Code/Java/foolish-football-master/game/target/classes:/root/.m2/repository/com/google/guava/guava/15.0/guava-15.0.jar:/root/.m2/repository/com/google/code/findbugs/jsr305/2.0.2/jsr305-2.0.2.jar:/root/.m2/repository/com/github/fommil/java-logging/1.1/java-logging-1.1.jar:/root/.m2/repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar:/root/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.5/jcl-over-slf4j-1.7.5.jar:/root/.m2/repository/org/slf4j/log4j-over-slf4j/1.7.5/log4j-over-slf4j-1.7.5.jar:/root/.m2/repository/org/slf4j/slf4j-jdk14/1.7.5/slf4j-jdk14-1.7.5.jar:/root/.m2/repository/org/ode4j/core/0.2.6/core-0.2.6.jar:/root/.m2/repository/org/ode4j/cpp/0.2.6/cpp-0.2.6.jar com.github.fommil.ff.Main
    Exception in thread "main" java.lang.IllegalArgumentException: no tactics directory in ../data/Sensible World of Soccer 96-97
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:93)
	at com.github.fommil.ff.swos.TacticsParser.getSwosTactics(TacticsParser.java:91)
	at com.github.fommil.ff.Main.main(Main.java:47)
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 2:12.506s
    [INFO] Finished at: Mon Sep 05 13:20:10 IST 2016
    [INFO] Final Memory: 10M/90M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project game: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
    org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project game: Command execution failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
    Caused by: org.apache.maven.plugin.MojoExecutionException: Command execution failed.
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:362)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
    Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:610)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:352)
	... 21 more
    [ERROR] 
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by fommil** [comment]
`java.lang.IllegalArgumentException: no tactics directory in ../data/Sensible World of Soccer 96-97`

you didn't install the data files. See README.

**Comment by kushtehlan** [comment]
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:java (default-cli) on project Demo: The parameters 'mainClass' for goal org.codehaus.mojo:exec-maven-plugin:1.5.0:java are missing or invalid 

Did anyone able to resolve this issue
